<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Version>1.0.2.0</Version>
    <FileVersion>1.0.2.0</FileVersion>

    <DebuggerSupport>false</DebuggerSupport>
    <EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
    <EnableUnsafeUTF7Encoding>false</EnableUnsafeUTF7Encoding>
    <EventSourceSupport>false</EventSourceSupport>
    <HttpActivityPropagationSupport>false</HttpActivityPropagationSupport>
    <UseSystemResourceKeys>true</UseSystemResourceKeys>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <PropertyGroup Condition="'$(SelfContained)' == 'true'">
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>partial</TrimMode>
    <_SuppressWinFormsTrimError>true</_SuppressWinFormsTrimError>
    <NoWarn>$(NoWarn);IL2008</NoWarn>
  </PropertyGroup>

  <Target Name="PublishStub" BeforeTargets="Publish" Condition="'$(SelfContained)' != 'true'">
    <Exec Command="dotnet publish &quot;$(ProjectDir)Lamarr&quot; -c $(Configuration) -r $(RuntimeIdentifier) --no-self-contained -p:PublishSingleFile=true -p:DebugType=none -p:DebugSymbols=false -o &quot;$(PublishDir)&quot;" />
    <Exec Command="dotnet build &quot;$(ProjectDir)LamarrPacker&quot; -c $(Configuration)" />
  </Target>

  <Target Name="LamarrPack" AfterTargets="Publish" Condition="'$(SelfContained)' != 'true'">
    <Exec Command="&quot;$(ProjectDir)LamarrPacker\bin\$(Configuration)\net8.0-windows\LamarrPacker.exe&quot; --stub &quot;$(PublishDir)Lamarr.exe&quot; --input &quot;$(ProjectDir)bin\$(Configuration)\$(TargetFramework)\win-x64\WeaponDamageCalc.dll&quot; --output &quot;$(PublishDir)WeaponDamageCalc_packed.exe&quot;" />
    <Copy SourceFiles="$(PublishDir)WeaponDamageCalc_packed.exe" DestinationFiles="$(PublishDir)WeaponDamageCalc.exe" OverwriteReadOnlyFiles="true" />
    <Delete Files="$(PublishDir)WeaponDamageCalc_packed.exe" />
  </Target>

  <ItemGroup>
    <Compile Remove="Lamarr\**" />
    <Compile Remove="LamarrPacker\**" />
    <EmbeddedResource Remove="Lamarr\**" />
    <EmbeddedResource Remove="LamarrPacker\**" />
  </ItemGroup>

  <ItemGroup>
    <None Update="weapons.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Tools\preset_file.txt" />
    <EmbeddedResource Include="Demo\keil.fc" />
  </ItemGroup>

  <ItemGroup Condition="'$(SelfContained)' == 'true'">
    <TrimmerRootAssembly Include="System.Windows.Forms" />
  </ItemGroup>

</Project>