<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <VersionPrefix>1.0</VersionPrefix>
    <VersionSuffix>$([System.DateTime]::Now.ToString("yy.Mdd"))</VersionSuffix>
    <FileVersion>$(VersionPrefix).$(VersionSuffix)</FileVersion>
    <Version>$(FileVersion)</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <None Update="weapons.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>