<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Version>1.0.2.0</Version>
    <FileVersion>1.0.2.0</FileVersion>

    <DebuggerSupport>false</DebuggerSupport>
    <EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
    <EnableUnsafeUTF7Encoding>false</EnableUnsafeUTF7Encoding>
    <EventSourceSupport>false</EventSourceSupport>
    <HttpActivityPropagationSupport>false</HttpActivityPropagationSupport>
    <UseSystemResourceKeys>true</UseSystemResourceKeys>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <Target Name="PublishStub" BeforeTargets="Publish" Condition="'$(SelfContained)' != 'true'">
    <Exec Command="cd /d &quot;$(ProjectDir)StubNative&quot; &amp;&amp; ml64 /c lamarr_stub.asm &amp;&amp; link /DLL /NOENTRY /SUBSYSTEM:WINDOWS lamarr_stub.obj /OUT:lamarr_stub.dll kernel32.lib" />
    <Exec Command="dotnet build &quot;$(ProjectDir)Patcher&quot; -c $(Configuration)" />
  </Target>

  <Target Name="LamarrPack" AfterTargets="Publish" Condition="'$(SelfContained)' != 'true'">
    <Exec Command="dotnet run --project &quot;$(ProjectDir)Patcher&quot; -- --stub &quot;$(ProjectDir)StubNative\lamarr_stub.dll&quot; --input &quot;$(ProjectDir)bin\$(Configuration)\$(TargetFramework)\win-x64\WeaponDamageCalc.dll&quot; --output &quot;$(PublishDir)WeaponDamageCalc.exe&quot;" />
  </Target>

  <ItemGroup>
    <Compile Remove="Lamarr\**" />
    <Compile Remove="LamarrPacker\**" />
    <EmbeddedResource Remove="Lamarr\**" />
    <EmbeddedResource Remove="LamarrPacker\**" />
  </ItemGroup>

  <ItemGroup>
    <None Update="weapons.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Tools\preset_file.txt" />
    <EmbeddedResource Include="Demo\keil.fc" />
  </ItemGroup>

</Project>