<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>LamarrPacker</AssemblyName>
    <RootNamespace>LamarrPacker</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Lamarr.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\Native\Boot\BundleStream.cs" Link="BundleStream.cs" />
  </ItemGroup>
</Project>