<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>LamarrNativePack</AssemblyName>
    <RootNamespace>Lamarr.NativePack</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Lamarr.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Boot\**" />
    <EmbeddedResource Remove="Boot\**" />
    <Compile Remove="BootAntheil\**" />
    <EmbeddedResource Remove="BootAntheil\**" />
  </ItemGroup>
</Project>